config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  
  root to: "top#index"

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :spots, only: [:index, :show] do
    resources :photos, only: [:create, :destroy]
    collection do
      get 'quiz'
      get 'jmap'
    end
  end

end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def previous
    Spot.where('id < ?', id).order('id DESC').first
  end

  def next
    Spot.where('id > ?', id).order('id ASC').first
  end
end

app/models/photo.rb
# frozen_string_literal: true

class Photo < ApplicationRecord
  belongs_to :user
  belongs_to :spot
  validates :text, :photo_image, presence: true

  mount_uploader :photo_image, ImageUploader
end

app/models/spot.rb
# frozen_string_literal: true

class Spot < ApplicationRecord
  has_many :photos, dependent: :destroy
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true, uniqueness: true, length: { maximum: 20 }
  validates :email, presence: true, uniqueness: true

  has_many :photos, dependent: :destroy

  def self.guest
    find_or_create_by!(email: 'guest@example.com', nickname: 'TESTUSER') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/photos_controller.rb
# frozen_string_literal: true

class PhotosController < ApplicationController
  before_action :set_spot

  def create
    photo = Photo.create(photo_params)
    if photo.save
      redirect_to spot_path(@spot), notice: 'あなたの思い出を追加しました'
    else
      @spot = Spot.find(photo.spot.id)
      @photo = Photo.new
      @photos = @spot.photos.includes(:user)
      flash.now[:alert] = '投稿にはタイトルと写真の両方が必要です'
      render 'spots/show'
    end
  end

  def destroy
    @photo = @spot.photos.find(params[:id])
    @photo.destroy
    redirect_to spot_path(@spot), notice: '削除が完了しました'
  end

  private

  def set_spot
    @spot = Spot.find(params[:spot_id])
  end

  def photo_params
    params.require(:photo).permit(:text, :photo_image).merge(user_id: current_user.id, spot_id: params[:spot_id])
  end
end

app/controllers/spots_controller.rb
# frozen_string_literal: true

class SpotsController < ApplicationController
  before_action :set_spot, only: %i[index jmap]

  def index; end

  def show
    @spot = Spot.find(params[:id])
    @photo = Photo.new
    @photos = @spot.photos.includes(:user).order('created_at DESC').page(params[:page]).per(6)
  end

  def quiz; end

  def jmap; end

  private

  def set_spot
    @spots = Spot.all
  end
end

app/controllers/top_controller.rb
# frozen_string_literal: true

class TopController < ApplicationController
  def index; end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :check_guest, only: %i[update destroy]

  def check_guest
    if resource.email == 'guest@example.com'
      redirect_to root_path, alert: 'テストユーザーの編集・削除はできません。'
    end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'テストユーザーとしてログインしました。'
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/photos_helper.rb
# frozen_string_literal: true

module PhotosHelper
end

app/helpers/spots_helper.rb
# frozen_string_literal: true

module SpotsHelper
end

app/helpers/top_helper.rb
# frozen_string_literal: true

module TopHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/layouts/_notifications.html.erb
<div class="notification">
  <% flash.each do |key, value| %>
    <%= content_tag :div, value, class: key %>
  <%end%>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="ja">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tag %>
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <%= stylesheet_link_tag "application", media: "all" %>
  <title>Tabijitaku app</title>
</head>

<body>
  <%= render 'layouts/notifications' %>
  <header class="sticky-top">
    <div class="container-fluid pl-5 pr-5 border-bottom">
      <nav class="navbar navbar-expand-sm navbar-light">
        <a href="/" class="navbar-brand">旅 じ た く</a>
        <button class="navbar-toggler" data-toggle="collapse" data-target="#menu">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div id="menu" class="flex-row-reverse collapse navbar-collapse ">
          <ul class="navbar-nav">
            <li class="nav-item"><a href="/spots" class="nav-link pr-3">一覧を見る</a></li>
            <li class="nav-item"><a href="/spots/jmap" class="nav-link pr-3">場所を覚える</a></li>
            <li class="nav-item"><a href="/spots/quiz" class="nav-link pr-3">クイズで学ぶ</a></li>
            <% if user_signed_in? %>
              <li class="nav-item"><%= link_to "アカウント編集",  edit_user_registration_path, class: 'nav-link text-primary pr-3' %> </li>
              <li class="nav-item"><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link text-danger' %> </li>
            <% else %>
              <%= link_to "ログイン・新規登録", new_user_session_path, class: 'nav-link text-primary pr-3' %> </li>
              <%= link_to "テストログイン", users_guest_sign_in_path, method: :post,  class: 'nav-link text-primary border border-primary' %> </li>

            <% end %>
          </ul>
        </div>
      </nav>
    </div>
  </header>


    <%= yield %>

  <footer class="text-center text-muted py-4 border-top mt-auto bg-light">
    引用文 :「5分でおさらい！日本にある23の世界遺産総まとめ」https://tg.tripadvisor.jp/news/advice/world-heritage_japan_all20/
  </footer>
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>

</html>

app/views/photos/_photo.html.erb
<div class="col-md-6 mb-4">
  <div class="photo-box">
    <%= image_tag photo.photo_image.url ,class: "mx-auto d-block"%>
    <p class="photo-text">【 <%= photo.text %> 】</p>
    <p class="photo-nickname"><%= photo.user.nickname %></p>
    <% if user_signed_in? && current_user.id == photo.user_id %>
      <%= link_to '✕', spot_photo_path(@spot, photo), method: :delete, class: "photo-destroy-btn btn btn-sm btn-outline-danger", data:
        {confirm: "この投稿を削除してよろしいですか？",
          cancel: "やめる",
          commit: "削除する"}, title: "削除の確認" %>
    <% end %>
  </div>
</div>

app/views/spots/index.html.erb
<section class="py-5">
  <h1 class="mb-5 text-center text-secondary">スポットを選択すると詳細ページへ移動します</h1>
  <div class="container">
    <ul class="nav nav-tabs">
      <li class="nav-item"><a href="#北海道" class="nav-link active mr-5" data-toggle="tab">北海道</a></li>
      <li class="nav-item"><a href="#東北" class="nav-link mr-5" data-toggle="tab">東北</a></li>
      <li class="nav-item"><a href="#関東" class="nav-link mr-5" data-toggle="tab">関東</a></li>
      <li class="nav-item"><a href="#中部" class="nav-link mr-5" data-toggle="tab">中部</a></li>
      <li class="nav-item"><a href="#近畿" class="nav-link mr-5" data-toggle="tab">近畿</a></li>
      <li class="nav-item"><a href="#中国" class="nav-link mr-5" data-toggle="tab">中国</a></li>
      <li class="nav-item"><a href="#九州" class="nav-link mr-5" data-toggle="tab">九州</a></li>
    </ul>
    <div class="tab-content py-5">
      <div id="北海道" class="tab-pane active">
        <% @spots.each do |spot| %>
          <% if spot.region == "北海道" %>
            <%= link_to spot do %>
              <div class="mb-5 border row d-flex justify-content-left align-items-center">
                <div class="spot-box col-lg-6 p-5">
                  <img src="<%= spot.image %>" class="w-100">
                </div>
                <div class="spot-box col-lg-5">
                  <h2 class="text-center mb-5 text-dark"><%= spot.name %></h2>
                </div>
              </div>
            <% end %>
          <% end %>
        <% end %>
      </div>

      <div id="東北" class="tab-pane">
        <% @spots.each do |spot| %>
          <% if spot.region == "東北" %>
            <%= link_to spot do %>
              <div class="mb-5 border row d-flex justify-content-left align-items-center">
                <div class="spot-box col-lg-6 p-5">
                  <img src="<%= spot.image %>" class="w-100">
                </div>
                <div class="spot-box col-lg-5">
                  <h2 class="text-center mb-5 text-dark"><%= spot.name %></h2>
                </div>
              </div>
            <% end %>
          <% end %>
        <% end %>
      </div>
      <div id="関東" class="tab-pane">
        <% @spots.each do |spot| %>
          <% if spot.region == "関東" %>
            <%= link_to spot do %>
              <div class="mb-5 border row d-flex justify-content-left align-items-center">
                <div class="spot-box col-lg-6 p-5">
                  <img src="<%= spot.image %>" class="w-100">
                </div>
                <div class="spot-box col-lg-5">
                  <h2 class="text-center mb-5 text-dark"><%= spot.name %></h2>
                </div>
              </div>
            <% end %>
          <% end %>
        <% end %>
      </div>
      <div id="中部" class="tab-pane">
        <% @spots.each do |spot| %>
          <% if spot.region == "中部" %>
            <%= link_to spot do %>
              <div class="mb-5 border row d-flex justify-content-left align-items-center">
                <div class="spot-box col-lg-6 p-5">
                  <img src="<%= spot.image %>" class="w-100">
                </div>
                <div class="spot-box col-lg-5">
                  <h2 class="text-center mb-5 text-dark"><%= spot.name %></h2>
                </div>
              </div>
            <% end %>
          <% end %>
        <% end %>
      </div>
      <div id="近畿" class="tab-pane">
        <% @spots.each do |spot| %>
          <% if spot.region == "近畿" %>
            <%= link_to spot do %>
              <div class="mb-5 border row d-flex justify-content-left align-items-center">
                <div class="spot-box col-lg-6 p-5">
                  <img src="<%= spot.image %>" class="w-100">
                </div>
                <div class="spot-box col-lg-5">
                  <h2 class="text-center mb-5 text-dark"><%= spot.name %></h2>
                </div>
              </div>
            <% end %>
          <% end %>
        <% end %>
      </div>
      <div id="中国" class="tab-pane">
        <% @spots.each do |spot| %>
          <% if spot.region == "中国" %>
            <%= link_to spot do %>
              <div class="mb-5 border row d-flex justify-content-left align-items-center">
                <div class="spot-box col-lg-6 p-5">
                  <img src="<%= spot.image %>" class="w-100">
                </div>
                <div class="spot-box col-lg-5">
                  <h2 class="text-center mb-5 text-dark"><%= spot.name %></h2>
                </div>
              </div>
            <% end %>
          <% end %>
        <% end %>
      </div>
      <div id="九州" class="tab-pane">
        <% @spots.each do |spot| %>
          <% if spot.region == "九州" %>
            <%= link_to spot do %>
              <div class="mb-5 border row d-flex justify-content-left align-items-center">
                <div class="spot-box col-lg-6 p-5">
                  <img src="<%= spot.image %>" class="w-100">
                </div>
                <div class="spot-box col-lg-5">
                  <h2 class="text-center mb-5 text-dark"><%= spot.name %></h2>
                </div>
              </div>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/spots/jmap.html.erb
<div class="container pt-4">
  <h1 class="mb-5 text-center text-secondary">日本地図で場所を覚える</h1>
  <h4 class="pb-3 text-primary">世界遺産によってはピンポイントで示せない場所もあるので、関連が深い場所を表示しています</h4>
  <p>①ピンをクリックするとそのスポットのリンクが表示されます。</p>
  <p>②クリックせずにカーソルをピンの上に置くと、世界遺産の登録名称を確認できます。</p>
  <div id="target"></div>
</div>

<style>
#target {
  width: 100%;
  height: 600px;
}
</style>


<script>
  function initMap() {
    var latlng = new google.maps.LatLng(36.5, 139);
    var target = document.getElementById('target');

    var map = new google.maps.Map(target, {
      center: latlng,
        zoom: 5,
        clickableIcons: false
      });

    <% @spots.each do |spot| %>
      (function () {
        
        var marker = new google.maps.Marker({
          position: {lat: <%= spot.latitude %>, lng: <%= spot.longitude %>},
          map: map,
          title: "<%= spot.name %>",
          icon: {
            url: "https://maps.google.com/mapfiles/ms/micons/green-dot.png",
          },
          animation: google.maps.Animation.BOUNCE
        });
        var spotLink = '<%= link_to "#{spot.address}", spot %>';

        var infoWindow = new google.maps.InfoWindow({
          position: {lat: <%= spot.latitude %>, lng: <%= spot.longitude %>},
          content: spotLink,
          pixelOffset: new google.maps.Size( 0, -20 )
          });
          marker.addListener('click', function(){
          infoWindow.open(map, marker);
          });          
      })();
    <% end %>
  }
</script>

<script src="https://maps.googleapis.com/maps/api/js?language=ja&region=JP&key=AIzaSyBsbAlSkry5YQYYQFHOYpLCtzjvQeqqqUw&callback=initMap" async defer></script>

app/views/spots/quiz.html.erb
<section id="wrapper" class="pt-5">
  <h1 class="mb-5 text-center text-light">クイズに挑戦してみよう！(全7問)</h1>
  <div class="container p-5 border rounded-lg border-light" id="qbox">
    <h2 id="question" class="mb-3"></h2>
    <ul id="choices" class="mb-3">
    </ul>
    <div id="btn" class="disabled">次の問題へ</div>

    <section id="result" class="hidden"> 
      <h3 class="mb-4"></h3>
      <a href="">もう一度解いてみる！</a>
    </section>
  </div>
</section>

<%= javascript_include_tag 'quiz.js' %>

app/views/spots/show.html.erb
    <div class="pagenation text-center pt-4">
      <% if @spot.previous.present? %>
        <%= link_to spot_path(@spot.previous) do %>
          <button class="btn btn-outline-info mr-4 p-2">◀ ◀ <%= @spot.previous.name %></button>
        <% end %>
      <% end %>
      <% if @spot.next.present? %>
        <%= link_to spot_path(@spot.next) do %>
          <button class="btn btn-outline-primary p-2"><%= @spot.next.name %> ▶ ▶</button>
        <% end %>
      <% end %>
    </div>
<div class="container">
  <div class="spot-wrapper border p-4 my-4">

    <h3 class="mt-5 mb-5 text-center border-bottom"><%= @spot.name %></h3>
    <div class="mb-5">
      <img src="<%= @spot.image %>" class="img-fluid mx-auto d-block">
      <div class="spot-box mt-5">
        <h4 class="text-justify text-align text-secondary"><%= @spot.content %></h4>
      </div>
    </div>
    <div id="target"></div>
  </div>

  <div class="photo-wrapper border py-5 px-3 my-4">
    <% if current_user %>
      <h4 class="text-center text-success mb-4 border-bottom">この世界遺産に関係する思い出を投稿できます （タイトルと写真両方必要です）</h4>
    
      <div class="form">
        <%= form_with(model: [@spot, @photo], local: true) do |form| %>
          <%= form.text_field :text, placeholder: "タイトルを入力してください", class: "form-group w-50 text-input mr-2" %>
          <%= form.file_field :photo_image, class: "file btn btn-outline-primary mb-2 mr-2" %>
          <%= form.submit "▶投稿する", class: "btn btn-success btn-lg form-group mb-2" %>
        <% end %>
      </div>
    <% else %>
      <strong><h3 class="text-center text-info">※※※ photoの投稿には新規登録/ログインが必要です ※※※</h3></strong>
    <% end %>

    <div class="photo-list">
      <h4 class="my-3">〜みんなの思い出〜 </h4>
      <div class="row">
        <% if @photos %>
          <%= render partial: "photos/photo", collection: @photos %>
        <% end %>
      </div>
    </div>
  </div>
</div>
  <div class="text-center">
    <div class="pagination d-inline-block"><%= paginate(@photos) %></div>
  </div>

  

<style>
#target {
  width: 100%;
  height: 400px;
}
</style>


<script>
    function initMap() {
      
      var target = document.getElementById('target');
      var map;
      var spot = {lat: <%= @spot.latitude %>, lng: <%= @spot.longitude %>};
      var marker;
      var infoWindow;

      map = new google.maps.Map(target, {
        center: spot,
        zoom: 8,
        mapTypeId: "hybrid"
      });

      marker = new google.maps.Marker({
        position: spot,
        map: map,
        icon: {
          url: "https://maps.google.com/mapfiles/ms/micons/red-dot.png",
        },
        animation: google.maps.Animation.BOUNCE
      });

      infoWindow = new google.maps.InfoWindow({
        position: spot,
        content: "<%= @spot.address %>",
        pixelOffset: new google.maps.Size( 0, -50 )
      });

    infoWindow.open(map);

    };
</script>

<script src="https://maps.googleapis.com/maps/api/js?language=ja&region=JP&key=AIzaSyBsbAlSkry5YQYYQFHOYpLCtzjvQeqqqUw&callback=initMap" async defer></script>

app/views/top/index.html.erb
<main>
  <div id="slides" class="carousel slide" data-ride="carousel">
  <ul class="carousel-indicators">
    <li data-target="#slides" data-slide-to="0" class="active"></li>
    <li data-target="#slides" data-slide-to="1"></li>
    <li data-target="#slides" data-slide-to="2"></li>
  </ul>
  <div class="carousel-inner">
    <div class="carousel-item ">
      <%= image_tag('bgimage1.jpeg') %>
        <div class="carousel-caption">
          <h2>Tabijitaku</h2>
        </div>
    </div>
    <div class="carousel-item">
      <%= image_tag('bgimage2.jpeg') %>
        <div class="carousel-caption">
          <h2>自宅で旅をはじめよう</h2>
        </div>

    </div>
    <div class="carousel-item active">
      <%= image_tag('bgimage3.jpeg') %>
        <div class="carousel-caption">
          <h2>日本の世界遺産を学ぶ</h2>
        </div>

    </div>
  </div>
  </div>

  <section class="py-5">
    <div class="container">
      <div class="mb-5 row d-flex justify-content-around align-items-center">
        <div class="col-md-8 order-md-1">
          <%= link_to spots_path do%>
            <h2 class="mb-3 text-dark"><u>一覧を見る</u></h2>
            <h3 class="text-dark">日本の世界遺産（全23ヶ所）を全て確認することができます！</h3>
            <p class="text-info">※ログインすることでその世界遺産に関する写真を投稿できます</p>
          <% end %>
        </div>
        <div class="col-md-4 order-md-2 ">
          <%= image_tag 'image2.jpeg', class: "w-100 mx-auto rounded-circle" %>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="mb-5 row d-flex justify-content-around align-items-center">
        <div class="col-md-8 order-lg-2">
          <%= link_to  jmap_spots_path do%>
            <h2 class="mb-3 text-dark"><u>場所を覚える</u></h2>
            <h3 class="text-dark">日本にある世界遺産を地図で全て確認できます！</h3>
          <% end %>
        </div>
        <div class="col-md-4 order-md-1">
          <%= image_tag 'image1.jpeg', class: "w-100 mx-auto rounded-circle" %>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="mb-5 row d-flex justify-content-around align-items-center">
        <div class="col-md-8 order-md-1">
          <%= link_to quiz_spots_path do%>
            <h2 class="mb-3 text-dark"><u>クイズで学ぶ</u></h2>
            <h3 class="text-dark">日本の世界遺産に関するクイズを解くことで、さらに詳しくなれます！</h3>
          <% end %>
        </div>
        <div class="col-md-4 order-md-2 ">
          <%= image_tag 'image3.jpeg', class: "w-100 mx-auto rounded-circle" %>
        </div>
      </div>
    </div>
  </section>

</main>